"""Pure NumPy Starlink PSS/SSS golden-oracle package."""

from .fixed import (
    ACCUMULATOR_BITS,
    ACCUMULATOR_MAX,
    ACCUMULATOR_MIN,
    COEFFICIENT_FRACTION_BITS,
    COMPONENT_BITS,
    FIXED_CORRELATOR_SCHEMA,
    FixedCorrelationResult,
    fixed_correlate_ci16,
    meets_rational_power_threshold,
    quantize_q15,
)
from .numerology import (
    FRAME_RATE_HZ,
    NATIVE_CYCLIC_PREFIX_SAMPLES,
    NATIVE_SAMPLE_RATE_HZ,
    NATIVE_USEFUL_SAMPLES,
    NUMEROLOGIES,
    SUBCARRIER_SPACING_HZ,
    StarlinkNumerology,
    numerology_for_rate,
)
from .search import FloatSearchResult, deterministic_float_search
from .waveforms import (
    PROJECTED_PSS_SHA256,
    PROJECTED_SSS_SHA256,
    PSS_NATIVE_SHA256,
    SSS_FREQUENCY_SHA256,
    SSS_NATIVE_SHA256,
    complex64_sha256,
    projected_pss,
    projected_sss,
    pss_native_time_samples,
    sss_frequency_symbols,
    sss_native_time_samples,
)

__all__ = (
    "ACCUMULATOR_BITS",
    "ACCUMULATOR_MAX",
    "ACCUMULATOR_MIN",
    "COEFFICIENT_FRACTION_BITS",
    "COMPONENT_BITS",
    "FIXED_CORRELATOR_SCHEMA",
    "FRAME_RATE_HZ",
    "NATIVE_CYCLIC_PREFIX_SAMPLES",
    "NATIVE_SAMPLE_RATE_HZ",
    "NATIVE_USEFUL_SAMPLES",
    "NUMEROLOGIES",
    "PROJECTED_PSS_SHA256",
    "PROJECTED_SSS_SHA256",
    "PSS_NATIVE_SHA256",
    "SSS_FREQUENCY_SHA256",
    "SSS_NATIVE_SHA256",
    "SUBCARRIER_SPACING_HZ",
    "FixedCorrelationResult",
    "FloatSearchResult",
    "StarlinkNumerology",
    "complex64_sha256",
    "deterministic_float_search",
    "fixed_correlate_ci16",
    "meets_rational_power_threshold",
    "numerology_for_rate",
    "projected_pss",
    "projected_sss",
    "pss_native_time_samples",
    "quantize_q15",
    "sss_frequency_symbols",
    "sss_native_time_samples",
)
