"""Generate the radio solver's Gram matrix from the pinned B04 integer bank."""
from __future__ import annotations

import argparse
import math
from pathlib import Path

from tools.starlink_glrt_native_abi import RATE, SAMPLES
from tools.starlink_glrt_native_replay import BANK_SHA256, coefficients


def generate(bank: bytes) -> str:
    rows = []
    for n, (ri,rq,di,dq) in enumerate(coefficients(bank)):
        reference = complex(ri,rq)
        rows.append((reference, -complex(di,dq),
                     1j*math.pi*1000/RATE*(2*n-(SAMPLES-1))*reference))
    gram = [[complex(math.fsum((r[i].conjugate()*r[j]).real for r in rows),
                     math.fsum((r[i].conjugate()*r[j]).imag for r in rows))
             for j in range(3)] for i in range(3)]
    values = ",\n".join("    {"+", ".join(
        f"{{{z.real.hex()}, {z.imag.hex()}}}" for z in row)+"}" for row in gram)
    return ("/* Generated by tools/generate_glrt_native_gram.py; do not hand edit. */\n"
            f"/* Exact integer coefficient bank SHA256: {BANK_SHA256} */\n"
            "/* Basis: reference, negative derivative per us, frequency derivative per kHz. */\n"
            "static const double native_gram[3][3][2] = {\n"+values+"\n};\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bank", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    with args.output.open("x") as output:
        output.write(generate(args.bank.read_bytes()))
