"""Generate rate/phase-bound radio solver bases from qualified integer ROMs."""
from __future__ import annotations

import argparse
import hashlib
import math
from pathlib import Path

from tools.starlink_glrt_native_replay import BANK_SHA256, coefficients

DIRECT_SHA256 = "dc509401673128c8f8d88cc8bd86790e11d783b354cb2d8316f386e2c94176e5"
PROFILES = tuple((2500000,phase) for phase in range(4)) + (
    (5000000,0),(15000000,0),(30000000,0),(60000000,0))


def reference_rows(cubic: bytes, direct: bytes, rate: int, phase: int):
    if (rate,phase) not in PROFILES:
        raise ValueError("unsupported tracking reference profile")
    if hashlib.sha256(cubic).hexdigest() != BANK_SHA256 or hashlib.sha256(direct).hexdigest() != DIRECT_SHA256:
        raise ValueError("tracking basis requires the pinned coefficient ROMs")
    if rate != 2500000:
        return coefficients(cubic, rate_hz=rate)
    words = [int(word,16) >> (64*phase) for word in direct.splitlines()]
    if len(words) != 3300:
        raise ValueError("incomplete direct reference ROM")
    def signed(value):
        return value-65536 if value & 32768 else value
    return [tuple(signed((word >> (16*k)) & 65535) for k in range(4)) for word in words]


def generate(cubic: bytes, direct: bytes) -> str:
    output = ["/* Generated by tools/generate_glrt_tracking_gram.py; do not hand edit. */",
              "/* Integer Q11 basis: reference, -derivative/us, frequency derivative/kHz. */",
              "static const struct tracking_basis tracking_bases[] = {"]
    for rate,phase in PROFILES:
        raw = reference_rows(cubic,direct,rate,phase)
        count, phases = len(raw), 4 if rate == 2500000 else 1
        rows = [(complex(ri,rq), -complex(di,dq),
                 1j*math.pi*1000/rate*(2*n-(count-1))*complex(ri,rq))
                for n,(ri,rq,di,dq) in enumerate(raw)]
        gram = [[complex(math.fsum((r[i].conjugate()*r[j]).real for r in rows),
                         math.fsum((r[i].conjugate()*r[j]).imag for r in rows))
                 for j in range(3)] for i in range(3)]
        digest = DIRECT_SHA256 if rate == 2500000 else BANK_SHA256
        output.append(f'    {{{{{rate}U, {count}U, {phase}U, {phases}U, {(phase/(rate*phases)).hex()}, "{digest}"}}, {{')
        output.extend("        {"+", ".join(f"{{{z.real.hex()}, {z.imag.hex()}}}" for z in row)+"},"
                      for row in gram)
        output.append("    }},")
    output.append("};")
    return "\n".join(output)+"\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cubic",type=Path,required=True)
    parser.add_argument("--direct",type=Path,required=True)
    parser.add_argument("--output",type=Path,required=True)
    args = parser.parse_args()
    generated = generate(args.cubic.read_bytes(),args.direct.read_bytes())
    with args.output.open("x") as output:
        output.write(generated)
